#!/usr/bin/env python -u -W ignore::DeprecationWarning
import sys
import boto.ec2
import getopt
import subprocess
import threading
import Queue
import shlex
import re
import os
import pickle
import time

# Create 3 global queues
"""
instanceid_and_tag
instanceid_and_dns
instanceid_and_name
"""
data_queues={'i_n_t' : None, 'i_n_d' : None, 'i_n_n' : None}
cache_file='/tmp/ssh-ec2.pickle'

for queue in data_queues:
    data_queues[queue] = Queue.Queue()

def start_workers():
    regions = boto.ec2.regions()
    workers=[]

    for region in regions:
        t = threading.Thread(target=work_on_region, args=(region.name,))
        workers.append(t)
        t.setDaemon(True)
        t.start()

    return workers

def work_on_region(region):

    i_n_t={}
    i_n_n={}
    i_n_d={}

    try:
        conn = boto.ec2.connect_to_region(region)
    except:
        print >>sys.stderr, 'Failed to connect to ' + str(region)
        sys.exit(1)
   
    try: 
        reservations = conn.get_all_instances()
    except:
        sys.exit(1)

    for reservation in reservations:
        for instance in reservation.instances:

            if instance.state == 'terminated':
                continue

            i_n_d[instance.id]=instance.public_dns_name

            # Lower all values in tag list
            i_n_t[instance.id] = map(lambda x: x.lower(), instance.tags.values())
            i_n_t[instance.id].append(instance.id)

            try:
                i_n_n[instance.id]=instance.tags.get('Name').lower()
            except:
                continue

    try:
        data_queues['i_n_t'].put(i_n_t)
        data_queues['i_n_n'].put(i_n_n)
        data_queues['i_n_d'].put(i_n_d)
    except:
        print >>sys.stderr, 'Failed to write to data queues'
        sys.exit(1)

def data_from_workers():

    # Dicts
    data_dicts={
        'i_n_t' : {},
        'i_n_n' : {},
        'i_n_d' : {},
    }

    for queue in data_queues:
        while data_queues[queue].qsize() > 0:
            try:
                data_dicts[queue].update(data_queues[queue].get())
            except Queue.Empty:
                print >>sys.stderr, 'Failed to read from ' + str(queue) + ' queue - empty' 
                sys.exit(1)
            except:
                print >>sys.stderr, 'Failed to read from ' + str(queue) + ' queue'
                sys.exit(1)

    return data_dicts

def data_from_cache():
    try:
        return pickle.load( open( cache_file, "rb" ) )
    except:
        print 'Failed to read cache - deleting cache'
        try:
            os.remove(cache_file)
        except:
            print 'Failed to delete cache - please delete %s manually' % (cache_file)

        sys.exit(1)


def data_to_cache(data_dicts):
    try:
        pickle.dump( data_dicts, open( cache_file, "wb" ) )
    except:
        print 'Failed to dump cache'
        sys.exit(1)

def instance_search(search_list, data_dicts):

    print 'Searching through ' + str(len(data_dicts['i_n_d'])) + ' servers'

    dict_of_sets={}
    found_instances=set()
    
    for keyword in search_list:
        keyword_string=str(keyword)
        for k, v in data_dicts['i_n_t'].iteritems():
            for v_tag in v:
                match = re.search(keyword, v_tag)
                if match:
                    if keyword not in dict_of_sets:
                        dict_of_sets[keyword_string]=set([k])
                    else:
                        dict_of_sets[keyword_string].add(k)

    for k, v in dict_of_sets.iteritems():
        if len(v) > 0:
            if len(found_instances) == 0:
                found_instances=v
            else:
                found_instances.intersection_update(v)

    return found_instances, data_dicts['i_n_n'], data_dicts['i_n_d']

def cache_exists():
    if os.path.isfile(cache_file):
        age = int((time.time() - os.path.getmtime(cache_file)) / 60)
        print 'Using %d minute old cache file' % ( age )
        return True
    else:
        return False

def usage():
    print >>sys.stderr, 'Usage:'
    print >>sys.stderr, '    ' + sys.argv[0] + " tag1 tag2... \tConnect to EC2 instance searched for by tag(s)"
    sys.exit(1)

def wait_for_workers(workers, done_waiting):
    if done_waiting:
        return

    # Summon threads
    for thread in workers:
        thread.join(2.0)

    data_dicts = data_from_workers()
    data_to_cache(data_dicts)

    return data_dicts

def main():

    index_selector={}
    target=None
    post_ssh_args=[]
    search_list=[]
    done_waiting=False

    if (len(sys.argv) < 2):
        usage()

    # Catch the regular stuff like help
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', ['help'])
    except getopt.GetoptError, err:
        print >>sys.stderr, str(err) 
        return 1

    for o, a in opts:
        if o == '-h' or o  == '--help':
            usage()
            sys.exit(0)

    # Catch the rest as search strings until we meet something starting with a -
    for arg in sys.argv[1:]:
        if arg ==  '--help':
            usage()
            sys.exit(0)
        elif arg.startswith('-') or arg.startswith('--') or len(post_ssh_args) > 0:
            post_ssh_args.append(arg)
        elif len(post_ssh_args) == 0:
            search_list.append(arg.lower())

    if len(search_list) == 0:
        print 'No search words defined'
        sys.exit(1)

    # Spawn workers as fast as possible
    workers = start_workers()

    if cache_exists():
        data_dicts = data_from_cache()
    else:
        data_dicts = wait_for_workers(workers, done_waiting)
        done_waiting=True

    found_instances, i_n_n, i_n_d=instance_search(search_list, data_dicts)

    if (len(found_instances) == 0):
        print 'No servers found'
        wait_for_workers(workers, done_waiting)
        sys.exit(1)

    if (len(found_instances) > 1):
        print 'We found multiple servers - please choose' 

        for index, instance_id in enumerate(found_instances):
            if len(i_n_d[instance_id]) == 0:
                print "({0:<3} {1:<10} {2:<20} {3}".format(index+1, instance_id, i_n_n[instance_id],  'stopped')
            else: 
                print "({0:<3} {1:<10} {2:<20} {3}".format(index+1, instance_id, i_n_n[instance_id], i_n_d[instance_id])
            index_selector[index+1]=instance_id
    
        try:
            selection = int(raw_input("Number: "))
            target=i_n_d[index_selector[selection]]
        except (KeyboardInterrupt):
            print '\nSee you..'
            wait_for_workers(workers, done_waiting)
            sys.exit(0)
        except (ValueError, IndexError, KeyError), e:
            print '\nInvalid choice: ' + str(e)
            wait_for_workers(workers, done_waiting)
            sys.exit(1)
        except:
            print '\nInvalid choice!'
            wait_for_workers(workers, done_waiting)
            sys.exit(1)

        instance_id=index_selector[selection]
        target=i_n_d[instance_id]
    else:
        instance_id=found_instances.pop()
        target=i_n_d[instance_id]

    if target in ['', None]:
        print 'Could not determine hostname from instance id %s (%s)' % (instance_id, i_n_n[instance_id])
        wait_for_workers(workers, done_waiting)
        sys.exit(1)

    ssh_args = 'ssh' + ' ' + str(target) + ' ' + ' '.join(post_ssh_args)
    ssh_args = shlex.split(ssh_args)

    print 'Connecting to ' + target 

    try:
        subprocess.call(ssh_args)
    except (KeyboardInterrupt):
        print '\nSee you..'
        wait_for_workers(workers, done_waiting)
        sys.exit(0)
    except:
        wait_for_workers(workers, done_waiting)
    else:
        wait_for_workers(workers, done_waiting)

if __name__ == "__main__":
    try:
        sys.exit(main())
    except (KeyboardInterrupt, SystemExit):
        sys.exit(0)
